name = "guidr-empire"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./out"

# Standard Next.js on Pages settings
[build]
command = "npm run build"
watch_dir = "app"

[triggers]
crons = ["0 9 * * *"]
